AdaCore/training_material

- courses/fundamentals_of_ada/120a_advanced_privacy.rst
- courses/fundamentals_of_ada/180a_multiple_inheritance.rst
- courses/fundamentals_of_ada/labs/180_polymorphism.lab.rst
- pandoc/pandoc_fe.py
With this option pandoc will fail when trying to eg include an image that does not exist, or use an undefined directive or symbol.
> Add --fail-if-warnings options to pandoc

- .github/workflows/main.yaml
- courses/fundamentals_of_ada/010_overview.rst
- courses/fundamentals_of_ada/200_elaboration.rst
- courses/fundamentals_of_ada/905_gnat_options.rst
- courses/fundamentals_of_ada/910_gpr_basics.rst
- courses/fundamentals_of_ada/915_predefined_libraries.rst
- courses/spark_for_ada_programmers/110_advanced_proof_techniques.rst
- courses/spark_for_ada_programmers/labs/020_formal_methods_and_spark.lab.rst
* Remove `gnatmake` (replaced by `gprbuild`)
* GPS -> GNAT Studio
* Spark -> SPARK (piggy backing on the PR)
See #1
> Remove deprecated tooling, rename Spark -> SPARK

- .github/workflows/main.yaml
Why APT needs MS ODBC DB driver is beyond me... 
https://www.meinekleinefarm.net/installing-the-microsoft-odbc-driver-for-sql-server-on-debian-linux-with-saltstack/
> Fix CI: Remove useless DB packages

- courses/fundamentals_of_ada/120_limited_types.rst
A quiz was way too large and hard to read, while having lots of redundant info, this makes it simpler by removing blabber around the important line.
> limited_type: remove expr fun from quizz

- courses/fundamentals_of_ada/120_limited_types.rst
- courses/fundamentals_of_ada/130_program_structure.rst
- courses/fundamentals_of_ada/180_polymorphism.rst
- courses/fundamentals_of_ada/200_elaboration.rst
- courses/fundamentals_of_ada/215_type_contracts.rst
- courses/fundamentals_of_ada/240_tasking.rst
Expression functions are a bit overused in the example, but they are an Ada 2012 construct and they are not introduced until later in the course. This set of commit replaces them with full expressions while trying to not make the slides too verbose.
> Remove expression functions

- courses/fundamentals_of_ada/190_exceptions.rst
- courses/fundamentals_of_ada/adv_190_exceptions.rst
Advanced exception contains slides about  re-raising, idioms, manipulating through identity.
I added those as slides to the "basic" but with much less examples, more as a general guide to what is possible.
> Split exceptions between basic and advanced

- courses/fundamentals_of_ada/230_interfacing_with_c.rst
- courses/fundamentals_of_ada/standard_course.txt
The "interfacing with C++" slides are wrongly named: there is ways to interface with C++ (mostly related to OOP) that are not even discussed there, the slides focus on the C FLI, which is not bad but it could misguide someone to present that as "interfacing with C++"
> Interfacing with C++ -> with C

- courses/spark_for_ada_programmers/010_course_overview.rst
- courses/spark_for_ada_programmers/020_formal_methods_and_spark.rst
- courses/spark_for_ada_programmers/030_spark_language_and_tools.rst
- courses/spark_for_ada_programmers/040_data_flow_analysis.rst
- courses/spark_for_ada_programmers/050_quantified_expressions.rst
Update the SPARK course to take into account latest updates:
- foward goto is supported
- all access types are supported (including access-to-constant)
- Ada.Text_IO spec is now in SPARK
> Update course, fix typos and remove whitespace at end of lines

- courses/fundamentals_of_ada/010_overview.rst
- pandoc/beamer_filter.py
- support_files/beamercolorthemeadacore.sty
Add the `:dfn:` role for definitions
Add a "Syntax" slide to overview displaying examples of syntax used in the slides
Modify the `:filename:` role to make it more distinct from normal text
Fix the `:command:` role to escape double-hyphens
> Pandoc: beamer implicit roles

- contrib/ci/package_labs.py
- courses/fundamentals_of_ada/labs/radar/020_declarations/instructions.rst
- courses/fundamentals_of_ada/labs/radar/030_basic_types/instructions.rst
- courses/fundamentals_of_ada/labs/radar/040_statements/instructions.rst
- courses/gnatstudio/getting_started_lab_1.rst
- courses/gnatstudio/navigate_debug_lab_2.rst
- courses/gnatstudio/support_files
- pandoc/lab_docs.py
- support_files/README.md
- support_files/docs_common.rst
When packaging labs, stop ignoring warnings and treat them as failures instead.
Improve the failure messages as well, by hiding the useless python stacktraces in case of subprogram failure.
> CI Labs: Early pkg failures

- pandoc/beamer_filter.py
A bug was introduced with the changes to the beamer filter: it no longer applied some roles, such as `answer`, this fixes this issue
> pandoc: beamer filter fix answer not displaying

- pandoc/beamer_filter.py
Beamer ignored unknown classes, this PR fixes this partially by checking that the first element of a directive is in a known class list
> beamer filter: more error for unknown classes

- courses/fundamentals_of_ada/020_declarations.rst
- courses/fundamentals_of_ada/030_basic_types.rst
- courses/fundamentals_of_ada/040_statements.rst
- courses/fundamentals_of_ada/050_array_types.rst
- courses/fundamentals_of_ada/060_record_types.rst
- courses/fundamentals_of_ada/065_type_derivation.rst
- courses/fundamentals_of_ada/070_subprograms.rst
- courses/fundamentals_of_ada/090_overloading.rst
- courses/fundamentals_of_ada/100_packages.rst
- courses/fundamentals_of_ada/110_private_types.rst
- courses/fundamentals_of_ada/130_program_structure.rst
- courses/fundamentals_of_ada/135_visibility.rst
- courses/fundamentals_of_ada/140_access_types.rst
- courses/fundamentals_of_ada/160_genericity.rst
- courses/fundamentals_of_ada/170_tagged_derivation.rst
- courses/fundamentals_of_ada/180_polymorphism.rst
- courses/fundamentals_of_ada/190_exceptions.rst
This PR adds definitions to the fundamental Ada classes (not adv or spec).
I added a definition under the following conditions: the term is new in the course, it is related to the class, it is defined in the RM, it can be understood from the paragraph or slides that follow.
I also changed some minor things: adding a definition for representation as "the memory-layout of an **object** of the type" (oversimplified but it gets the point accross); and making an element bold and a "tagged" as `:ada:`
> Add definitions as `:dfn:`, minor fixes

- contrib/quiz.py
- contrib/quiz_update.py
If quiz.py failed, it early-exited because of epycs default behaviour. Fixing that.
> Quiz update: black, fix early exit

- courses/fundamentals_of_ada/180_polymorphism.rst
Fix a wrong sentence "is a primitive of `T'Class`": Class-wide cannot have primitives see RM 3.4-4
Fix tagged types declarations
> Polymorphism: fix wrong sentence, and tagged declarations

- courses/fundamentals_of_ada/240_tasking.rst
- courses/fundamentals_of_ada/adv_240_tasking.rst
Use `task type T` instead of `task T` for ease of understanding.
Exception are where it makes sense: for brievity, or when explaining anonymous task types.
Also fixes a type where the `task body` was incorrectly declared.
> Task: adv and simple: fix, use named task tasks by default

- courses/fundamentals_of_ada/120_limited_types.rst
The slide was simply reiterating what any kind of aggregate can do, that was super confusing!
Adding a :dfn: so that trainees have a way to lookup more on the subject.
> Limited Aggregates: remove slide

- courses/codepeer/010_codepeer.rst
- fix back labs titles
- static analysis: fix typos
- gprbuild course
- codepeer: typo
> CodePeer: example typo with postcondition

- courses/codepeer/010_codepeer.rst
- courses/codepeer/labs/cruise/instructions.rst
- courses/codepeer/labs/radar/instructions.rst
Also fixes an (incorrect) instance of `-show-message -only`
> CodePeer switches are now `--option`

- courses/fundamentals_of_ada/050_array_types.rst
- courses/fundamentals_of_ada/060_record_types.rst
- courses/fundamentals_of_ada/adv_060_discriminated_record_types.rst
Add quizzes to the basic slides for unconstrained arrays, and discriminated records.
The advanced discriminated record was using an old version of the slides, which had been rewritten, and was using the improper "Variant records" to mean RM-defined "discriminated records" and "varying length array" to mean RM-defined "unconstrained arrays".
This is based on the outdated #187 which I reworked and rebased onto master.
> Unconstrained type quiz and adv rework

- .github/workflows/main.yaml
Only warning that remains is related to using the GNAT CE action, which will be fixed with #277
> CI: Fix deprecation warnings

- .github/workflows/main.yaml
- contrib/ci/alr_gnat_env.profile
- contrib/ci/lab_env.profile
Use GNAT FSF using Alire
This is done through several adaptations:
+ the PATH needs to be updated to point to the local alr download for GNAT and GPRbuild binaries
+ python and pip are installed from Ubuntu 22.04 repos
+ this bring in a new pytest which requires ignoring a file which looks like a test but is not
> CI: Use Alire for tests

- courses/static_analysis_via_compiler/010_static_analysis_via_compiler.rst
This PR adds slides to list the GNAT-specific options for warnings, style
This is necessary for the GNAT internal training, but may be skipped in other cases?
> static ana via comp: list GNAT-specific

- courses/fundamentals_of_ada/adv_270_subprogram_contracts.rst
This PR does cosmetic as well as presentation changes. The content is kept but it is reordered
Content changes:
* Contract-Based Programming -> Design-by-Contract ("official" name)
* Add explicit "Defensive Programming" slide
* Add general Quizzes
* Add example and associated table with Pre / Post vs Requirement / Guarantee
* Add dedicated "Visibility" slide for Pre / Post function calls
* Pre and post are defined on the same slide
* Dedicated "assertion policy" slide
Cosmetical:
* Add :dfn:, bold
* Add mono formatting for some pieces of code
> Subprogram contracts: Refactor

- courses/spark_for_ada_programmers/10_advanced_proof.rst
- courses/spark_for_ada_programmers/11_advanced_flow_analysis.rst
- courses/spark_for_ada_programmers/12_pointer_programs.rst
- courses/spark_for_ada_programmers/13_autoactive_proof.rst
- courses/spark_for_ada_programmers/14_state_abstraction.rst
- courses/spark_for_ada_programmers/15_spark_boundary.rst
- courses/spark_for_ada_programmers/1_course_overview.rst
- courses/spark_for_ada_programmers/2_formal_methods_and_spark.rst
- courses/spark_for_ada_programmers/3_spark_language.rst
- courses/spark_for_ada_programmers/4_spark_tools.rst
- courses/spark_for_ada_programmers/5_flow_analysis.rst
- courses/spark_for_ada_programmers/6_proof.rst
- courses/spark_for_ada_programmers/7_specification_language.rst
- courses/spark_for_ada_programmers/8_subprogram_contracts.rst
- courses/spark_for_ada_programmers/9_type_contracts.rst
- courses/spark_for_ada_programmers/labs/10_advanced_proof.lab.rst
- courses/spark_for_ada_programmers/labs/12_pointer_programs.lab.rst
- courses/spark_for_ada_programmers/labs/13_autoactive_proof.lab.rst
The following changes are taken into account:
- checking function termination is now the default
- annotation Always_Returns has been replaced by aspect Always_Terminates
- exception handlers are now supported
- SPARKlib now requires copying and adapting the project file
Also introduce space when possible between bullet points.
> Update SPARK course material for SPARK Pro 24
