contrib/sort_keywords.py
courses/fundamentals_of_ada/010_overview.rst
courses/fundamentals_of_ada/020_declarations.rst
courses/fundamentals_of_ada/030_basic_types.rst

I am performing a review of the Ada course slide by slide.
The changes are limited and mostly cosmetic.

Fundamentals of Ada review

---

courses/fundamentals_of_ada/020_declarations.rst
courses/fundamentals_of_ada/030_basic_types.rst
courses/fundamentals_of_ada/040_statements.rst

+ BNF course is removed
+ Syntax is somewhat close to BNF but not BNF, as for the rest of the coming classes

Remove BNF from 020, 030, 040

---

courses/fundamentals_of_ada/020_declarations.rst
courses/fundamentals_of_ada/030_basic_types.rst
courses/fundamentals_of_ada/040_statements.rst

Chapters 020, 030, 040 reviewed.
+ Bullet points
+ Reorder a bit
+ Merged some slides

020 030 040 - Review

---

pandoc/pandoc_fe.py

Pandoc left a huge useless stacktrace in case of error, now this is not the case anymore: clean and unambiguous errors :)

pandoc more silent in case of error

---

courses/fundamentals_of_ada/080_expressions.rst
courses/fundamentals_of_ada/080a_quantified_expressions.rst

Add Ada 2012 for conditonals, remove a redondant statement, add back lab to quantified expr

Expressions fixes

---

courses/spark_for_ada_programmers/060_contracts.rst
courses/spark_for_ada_programmers/070_type_contracts.rst
courses/spark_for_ada_programmers/080_proving_programs_correct.rst
courses/spark_for_ada_programmers/090_proving_absence_of_run_time_errors.rst
courses/spark_for_ada_programmers/100_the_proof_cycle.rst
courses/spark_for_ada_programmers/110_advanced_proof_techniques.rst
courses/spark_for_ada_programmers/120_depends_contract_and_information_flow_analysis.rst
courses/spark_for_ada_programmers/130_state_abstraction.rst
courses/spark_for_ada_programmers/140_interfacing_to_other_languages.rst
courses/spark_for_ada_programmers/150_crossing_the_spark_boundary.rst
courses/spark_for_ada_programmers/160_interfacing.rst
courses/spark_for_ada_programmers/170_designing_for_spark.rst
courses/spark_for_ada_programmers/180_adoption_guidance.rst

Automatically done by editor, to avoid mixing with semantic changes later.

Just removal of white space

---

courses/fundamentals_of_ada/080_expressions.rst
courses/fundamentals_of_ada/adv_080_quantified_expressions.rst
courses/fundamentals_of_ada/labs/080_expressions.lab.rst
courses/fundamentals_of_ada/labs/adv_080_expressions.lab.rst
courses/fundamentals_of_ada/labs/answers/080_expressions.txt
courses/fundamentals_of_ada/labs/answers/adv_080_expressions.txt
courses/fundamentals_of_ada/labs/prompts/080_expressions/main.adb
courses/fundamentals_of_ada/labs/prompts/adv_080_expressions/default.gpr
courses/fundamentals_of_ada/labs/prompts/adv_080_expressions/main.adb

Move all indications of Quantified Expressions into Advanced module

---

courses/fundamentals_of_ada/240_tasking.rst
courses/fundamentals_of_ada/labs/240_tasking.lab.rst
courses/fundamentals_of_ada/labs/adv_240_tasking.lab.rst
courses/fundamentals_of_ada/labs/answers/240_tasking.txt
courses/fundamentals_of_ada/labs/prompts/240_tasking/default.gpr
courses/fundamentals_of_ada/labs/prompts/240_tasking/main.adb
courses/fundamentals_of_ada/labs/prompts/240_tasking/protected_object.adb
courses/fundamentals_of_ada/labs/prompts/240_tasking/protected_object.ads
courses/fundamentals_of_ada/labs/prompts/240_tasking/task_type.adb
courses/fundamentals_of_ada/labs/prompts/240_tasking/task_type.ads
courses/fundamentals_of_ada/labs/prompts/adv_240_tasking/counter.adb
courses/fundamentals_of_ada/labs/prompts/adv_240_tasking/counter.ads
courses/fundamentals_of_ada/labs/prompts/adv_240_tasking/datastore.adb
courses/fundamentals_of_ada/labs/prompts/adv_240_tasking/datastore.ads
courses/fundamentals_of_ada/labs/prompts/adv_240_tasking/default.gpr
courses/fundamentals_of_ada/labs/prompts/adv_240_tasking/main.adb

Add lab for fundamental version; change name of lab for advanced version to "advanced"; add prompt for advanced lab

240 tasking updates

---

contrib/adacut.py

Updates the adacut tool to add the cut type, which allows creating extracts from a working project, with automatic ellipses.

adacut "cut" type

---

courses/fundamentals_of_ada/labs/answers/spec_891_ada_characters.txt
courses/fundamentals_of_ada/labs/prompts/spec_891_ada_characters/default.gpr
courses/fundamentals_of_ada/labs/prompts/spec_891_ada_characters/main.adb
courses/fundamentals_of_ada/labs/spec_891_ada_characters.lab.rst
courses/fundamentals_of_ada/spec_891_ada_characters.rst

First new predefined library module

---

courses/fundamentals_of_ada/065_type_derivation.rst
courses/fundamentals_of_ada/adv_065_primitives.rst

This adds a new 065_advanced_primitives chapter that contains more info about primitives.
This simplifies as a result the way primitives and freeze-point are described in the usual set of slides.

Advanced 065 derivation primitive chapter

---

pandoc/beamer_filter.py

Re-enable the filter errors
Disable the exception to debug handling
Remove the debug file
Add a "fail" function

Pandoc: Fails early

---

pandoc/pandoc_fe.py

Refactor pandoc FE script, and improve its performances by making it run in parallel when working with several files.
+ Black
+ Add the -j flag (default -j0)

Pandoc: Parallel runs

---

.github/workflows/main.yaml
courses/fundamentals_of_ada/advanced.txt

This simply adds the advanced course content list, and integrates it into the CI.

Advanced: Syllabus

---

courses/fundamentals_of_ada/adv_240_tasking.rst

- adv 240: advanced tasking title
- adv 240: move select up
- adv 240: fix missing code
- adv 240: quiz
- adv 240: add quiz

Advanced Tasking: Quiz + Fix

---

courses/fundamentals_of_ada/adv_030_basic_types.rst

- adv subtypes: quiz
- lint 030

Advanced Type: Quiz

---

.github/workflows/main.yaml
contrib/quiz.py
contrib/quiz_update.py

This PR does not add any quiz but adds a small fix to the quiz utility and adds `quiz_update.py` to update the file `quiz.rst` for all the quiz that exist.
This script is also integrated in CI to perform automatic checks that the quizes are up-to-date.

CI: Quiz update

---

courses/fundamentals_of_ada/adv_240_tasking.rst

- adv 240 tasking: wording
- adv 240: move question around

Advanced 240 Tasking: Move quiz, rephrase sentence

---

courses/fundamentals_of_ada/labs/solar_system/050_array_types/answers/main.adb
courses/fundamentals_of_ada/labs/solar_system/050_array_types/src/main.adb

- lab radar: remove if-expression reference
- solar 050: clarify comments and format

Labs: Solar 050 Array format

---

courses/fundamentals_of_ada/labs/solar_system/start_linux_x86-64.sh

- lab radar: remove if-expression reference
- Solar system lab : Linux support for VSCode

Lab solar linux VSCode support

---

courses/fundamentals_of_ada/120_limited_types.rst

It feels out of place to have such a basic remark taking a whole slide
on an advanced subject. Furthermore, it is already covered in details
on the "Subprograms" chapter

120: remove limited aggregate in/out slide

---

pandoc/beamer_filter.py

Helps with portability of the tooling to BSD

beamer filter: make executable

---

courses/fundamentals_of_ada/labs/solar_system/start_windows_x86-64.bat
extern/gnat_sdl/gnat_sdl.gpr

- default SDL for windows: SDL2
- fix sdl start gnatstudio

Fix SDL lab start script + default SDL

---

courses/fundamentals_of_ada/140_access_types.rst
courses/fundamentals_of_ada/adv_140_access_types.rst

- adv_140 fix
- 140: ported access check from adv_140

Fix access depth, add back null slide

---

.github/workflows/main.yaml
contrib/adacut.py
contrib/ci/build_labs_check.py
contrib/ci/check_images.py
contrib/ci/fix_prelude.py
contrib/ci/package_labs.py
contrib/ci/slides.py
contrib/rst_update_prelude.py
contrib/sort_keywords.py
contrib/testsuite/test_adacut.py
courses/fundamentals_of_ada/labs/radar/test_all.py
pandoc/beamer_filter.py
pandoc/lab_docs.py
pandoc/parse_pandoc_defaults.py

No content change at all, it should be isofunctional.
Add a black lint check to the CI.

Lint python scripts with black

---

courses/fundamentals_of_ada/adv_030_basic_types.rst

- advanced class
- adv 030: gnat intrinsic shift rotate

Advanced types: Modular shift rotate using GNAT's intrinsics

---

courses/fundamentals_of_ada/adv_060_discriminated_record_types.rst

* :dfn: discriminant, and variant
* field -> component (field is not used by the RM or UG)
* Tag in example -> Group (could be mistaken for tagged types!)

Discriminated Records: names fix, add :dfn:

---

courses/fundamentals_of_ada/020_declarations.rst

New Ada2022 keyword "parallel"
Explicitly call out exponent must be integer (to make following quiz easier) Reformat comparison between untyped and typed named numbers

Add new information plus formatting change

---

contrib/quiz.py
contrib/quiz_update.py
courses/fundamentals_of_ada/adv_030_basic_types.rst
courses/fundamentals_of_ada/quiz/user_defined_character/prj.gpr
courses/fundamentals_of_ada/quiz/user_defined_character/quiz.rst
courses/fundamentals_of_ada/quiz/user_defined_character/template/main.adb

- quiz script update for fulltext answers
- quiz example

Type: fix Quiz on character type

---

courses/fundamentals_of_ada/adv_250_containers.rst
courses/fundamentals_of_ada/examples/containers/extracts.toml
courses/fundamentals_of_ada/examples/containers/extracts/compare.adb
courses/fundamentals_of_ada/examples/containers/extracts/decl_instances.adb
courses/fundamentals_of_ada/examples/containers/extracts/decl_map.ads
courses/fundamentals_of_ada/examples/containers/extracts/decl_set.ads
courses/fundamentals_of_ada/examples/containers/extracts/decl_vector.ads
courses/fundamentals_of_ada/examples/containers/extracts/insert.adb
courses/fundamentals_of_ada/examples/containers/extracts/iterate.adb
courses/fundamentals_of_ada/examples/containers/extracts/search.adb
courses/fundamentals_of_ada/examples/containers/extracts/sort.adb
courses/fundamentals_of_ada/examples/containers/prj.gpr
courses/fundamentals_of_ada/examples/containers/src/integer_vectors.adb
courses/fundamentals_of_ada/examples/containers/src/integer_vectors.ads
courses/fundamentals_of_ada/examples/containers/src/main.adb
courses/fundamentals_of_ada/examples/containers/src/named_constants_maps.ads
courses/fundamentals_of_ada/examples/containers/src/string_id_sets.ads

- add vector example
- add map
- sets
- clarify containers
- example extract tool + container examples
- sorting
- gnatpp
- search

Containers: add slides and examples

---

courses/spark_for_ada_programmers/060_contracts.rst
courses/spark_for_ada_programmers/070_type_contracts.rst
courses/spark_for_ada_programmers/100_the_proof_cycle.rst

Relocalize sections in other chapters.
Change order and content of features presented.

Rework the chapter on subprogram contracts

---

.github/workflows/main.yaml

- fix back labs titles
- static analysis: fix typos
- gprbuild course

GPRbuild: build standard course with CI

---

courses/codepeer/010_codepeer.rst

- fix back labs titles
- static analysis: fix typos
- gprbuild course
- codepeer: typo
- codepeer: remove the deprecated MessagePatterns.xml

CodePeer: rm MessagePatterns.xml (deprecated)

---

courses/spark_for_ada_programmers/1_course_overview.rst
courses/spark_for_ada_programmers/2_formal_methods_and_spark.rst
courses/spark_for_ada_programmers/3_spark_language.rst
courses/spark_for_ada_programmers/4_spark_tools.rst
courses/spark_for_ada_programmers/5_flow_analysis.rst
courses/spark_for_ada_programmers/6_proof.rst

This is based on PR #295 and adds some dfn, as well as some emphasis onto chapter 1-5 of the new SPARK course

New SPARK course, format improvements

---

contrib/ci/check_images.py
contrib/quiz.py
courses/spark_for_ada_programmers/7_specification_language.rst
courses/spark_for_ada_programmers/8_subprogram_contracts.rst
courses/spark_for_ada_programmers/9_type_contracts.rst
pandoc/beamer_filter.py
pandoc/pandoc_fe.py

Continuation of the work done in #298, itself a follow up of #295
This improves formating, and add dfn for chapters 6-10 of the new SPARK course

New SPARK course, format reword, day 2

---

courses/fundamentals_of_ada/050_array_types.rst

- arrays : T'Range -> O'Range
- array: remove weird membership test
- Real -> Float
- typo

Array small fixes

---

pandoc/pandoc_fe.py

Pandoc filter: refactorize by adding `parse_rst_list_file()`

RST list: add support for comment, empty lines

---

.github/workflows/main.yaml

Taken from https://stackoverflow.com/questions/64635032/github-actions-run-on-push-to-all-branches

GitHub Actions run on pull-request to all branches

---

courses/fundamentals_of_ada/060_record_types.rst

This slide simply introduces the concept wrt constant, because limited are actually talked about in a lot of later contexts (generics, privates...)

Records: Add slide for early limited introduction

---

courses/fundamentals_of_ada/gnat.txt
courses/fundamentals_of_ada/intro_160_genericity.rst

Those slides are simply extracted from the genericity class, with some quizes added on top
Depends on #325

Add intro to genericity slides

---

courses/fundamentals_of_ada/README.md
courses/fundamentals_of_ada/intro_160_genericity.rst

- fix pandoc filter HTML generation
- improve README
- fix clipped content
- semicolon
- typos in quiz
- review: add :ada:

Intro to Genericy - Review fixes

---

courses/fundamentals_of_ada/gnat.txt

GNAT internal: present expression functions right before expressions

---

courses/fundamentals_of_ada/135_visibility.rst

```
package Enum is
type A is (B, C, D);
end Enum;
---------------------
with Enum;
procedure Main is
O : Enum.A := Enum.B;
use type Enum.A;
O2 : Enum.A := Enum.B;
begin
declare
use all type Enum.A;
begin
O := B;
end;
end Main;
```

visib: `use all type` enumerals are direct. visib.
